### ISSUE TITLE
Fix file paths on Windows

### ISSUE THREAD

**Issue by bpugh** [turadg/lazyspec#4]
Since node path operations on windows have backslashes then the import statements end up looking like this:
```javascript
import Panel from '..\..\..\components\shared\Panel.jsx';
```
and also seems to cause issues with saving the spec file.

A fix that worked for me locally was to just replace the backslashes with forwardslashes:
```javascript
const importPath = path.relative(specPath, unitPath).slice(3).replace(/\\/g, '/');
```

I can submit a PR if you don't see an issue with this solution.

Update: I also verified this fix causes the tests in `generateSpecFile-test.js` to pass on windows

**Comment by turadg** [comment]
Thanks for raising this @bpugh . I don't see any issues with the solution, though I don't have any experience with Node on Windows so that doesn't mean much. :)

In any case, I'd gladly accept that PR. Maybe with a little comment explaining why the replace is needed.
